server:
  port: 8090
  servlet:
    context-path: /api/v1
  max-http-request-header-size: 40MB

spring:
  config:
    activate:
      on-profile: prod

  main:
    allow-bean-definition-overriding: true

  security:
    filter:
      order: 10

# 파일 업로드 용량 설정
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.url}:${db.port}/${db.schema}
    username: ${db.username}
    password: ${db.password}

  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_insert: true
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

jwt:
  header: Authorization
  secret: pastisjustpast
  token-validity-in-seconds: 86400

log:
  config:
    path: ./logs
    filename: console

error:
  log:
    config:
      filename: error