spring:
  config:
    activate:
      on-profile: local


  datasource:
    url: jdbc:h2:tcp://localhost/~/kbsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_insert: true
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          discord:
            clientId: 1072886733156384929
            clientSecret: XB8S2F5XaV_G9tv-nwxWUGcTYh8SlW2Z
            scope:
              - email
            redirectUri: "http://localhost:8080/api/v1/auth/discord"
            authorizationGrantType: authorization_code
            clientName: discord
            clientAuthenticationMethod: POST
        provider:
          discord:
            authorizationUri: https://discord.com/oauth2/authorize
            tokenUri: https://discord.com/api/oauth2/token
            userInfoUri: https://discord.com/api/v8/users/@me