server:
  port: ${port:8090}
  servlet:
#    context-path: /api/v1
    max-http-header-size: 40MB

spring:
  main:
    allow-bean-definition-overriding: true

  devtools:
    add-properties: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

logging:
  level:
    com.example: DEBUG
# org.hibernate.type: trace

jwt:
  header: Authorization
  secret: pastisjustpastpastisjustpastpastisjustpastpastisjustpastpastisjustpastpastisjustpastpastisjustpastpastisjustpast
  token-validity-in-seconds: 86400